plugins {
    id 'com.android.application' version '7.0.4' apply false
    id 'com.android.library' version '7.0.4' apply false
    id 'org.jetbrains.kotlin.android' version '1.5.31' apply false
    id 'io.codearte.nexus-staging' version '0.11.0'
}

ext {
    kotlinVersion = '1.5.31'
    koinVersion = '2.0.1'
    espressoVersion = '3.2.0'
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
        mavenLocal()
        maven { url 'https://jitpack.io' }
        maven {
            url "http://acra.googlecode.com/svn/repository/releases"
            allowInsecureProtocol = true
        }
        maven { url "https://repo.maven.apache.org/maven2" }
        maven {
            url "http://cloudant.github.io/cloudant-sync-eap/repository"
            allowInsecureProtocol = true
        }
        maven { url "https://s3.amazonaws.com/repo.commonsware.com" }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
        maven { url "https://plugins.gradle.org/m2/" }
    }
}

subprojects {
    ext.androidBuildToolsVersion = '30.0.3'
}

configure(allprojects) { project ->
    version = VERSION_NAME
    group = GROUP
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

def isReleaseBuild() {
    return version.contains("SNAPSHOT") == false
}
