// Top-level build file where you can add configuration options common to all sub-projects/modules.

apply plugin: 'com.github.kt3k.coveralls'

buildscript {
    ext.kotlinVersion = '1.8.22'
    ext.koinVersion = '2.0.1'
    ext.espressoVersion = '3.2.0'
    ext.dokkaVersion = '0.10.1'
    repositories {
        google()
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath 'gradle.plugin.org.kt3k.gradle.plugin:coveralls-gradle-plugin:2.10.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath "org.jetbrains.dokka:dokka-gradle-plugin:${dokkaVersion}"
        classpath 'com.dicedmelon.gradle:jacoco-android:0.1.5'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        mavenLocal()
        maven { url 'https://jitpack.io' }
        maven {
            url "http://acra.googlecode.com/svn/repository/releases"
            allowInsecureProtocol = true
        }
        maven { url "https://repo.maven.apache.org/maven2" }
        maven {
            url "http://cloudant.github.io/cloudant-sync-eap/repository"
            allowInsecureProtocol = true
        }
        maven { url "https://s3.amazonaws.com/repo.commonsware.com" }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
        maven { url "https://plugins.gradle.org/m2/" }
    }
}
subprojects {
    ext.androidBuildToolsVersion = '33.0.2'

    configurations.all {
        exclude group: 'com.google.guava', module: 'listenablefuture'

        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == "com.google.android.gms" &&
                    details.requested.name.startsWith("play-services-measurement")) {
                details.useVersion "21.3.0"
            }
            if (details.requested.group == "org.jetbrains.kotlin" &&
                    details.requested.name.startsWith("kotlin-stdlib")) {
                details.useVersion kotlinVersion
            }
        }
    }

    tasks.matching { it.name.toLowerCase().startsWith("lint") }.configureEach {
        enabled = false
    }

    tasks.withType(Test).configureEach {
        enabled = false
    }
}

configure(allprojects) { project ->

    version = VERSION_NAME
    group = GROUP
    buildscript {
        repositories {
            google()
            jcenter()
            mavenCentral()
            maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
            mavenLocal()
            maven { url "https://plugins.gradle.org/m2/" }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

def isReleaseBuild() {
    return version.contains("SNAPSHOT") == false
}
