import org.gradle.api.publish.maven.MavenPublication

apply plugin: 'signing'

def mavenLocalFlag = hasProperty('mavenLocal') ? mavenLocal.toBoolean() : true
def timestampMsg = " at " + getDate()

if (isReleaseBuild()) {
    println 'PROCESSING MAVEN ' + (mavenLocalFlag ? 'LOCAL' : 'REMOTE') + ' RELEASE BUILD VERSION ' + project.VERSION_NAME + timestampMsg + '...'
} else {
    println 'PROCESSING MAVEN ' + (mavenLocalFlag ? 'LOCAL' : 'REMOTE') + ' SNAPSHOT BUILD VERSION ' + project.VERSION_NAME + timestampMsg + '...'
}

def getRepositoryPassword() {
    return hasProperty('sonatypePassword') ? sonatypePassword : ""
}

def getRepositoryUsername() {
    return hasProperty('sonatypeUsername') ? sonatypeUsername : ""
}

def getDate() {
    return new Date().format('yyyy-MM-dd HH:mm:ss')
}

afterEvaluate { project ->
    def androidJavadocs = tasks.register("androidJavadocs", Javadoc) {
    }

    def androidJavadocsJar = tasks.register("androidJavadocsJar", Jar) {
        dependsOn androidJavadocs
        archiveClassifier.set('javadoc')
    }

    def androidSourcesJar = tasks.register("androidSourcesJar", Jar) {
        archiveClassifier.set('sources')
        from android.sourceSets.main.java.srcDirs
    }

    publishing {
        publications.withType(MavenPublication).configureEach { publication ->
            artifactId = POM_SETTING_ARTIFACT_ID
            artifact androidSourcesJar
            artifact androidJavadocsJar

            pom {
                name = POM_SETTING_NAME
                description = POM_SETTING_DESCRIPTION
                url = POM_SETTING_URL

                licenses {
                    license {
                        name = POM_SETTING_LICENCE_NAME
                        url = POM_SETTING_LICENCE_URL
                        distribution = POM_SETTING_LICENCE_DIST
                    }
                }

                developers {
                    developer {
                        id = POM_SETTING_DEVELOPER_ID
                        name = POM_SETTING_DEVELOPER_NAME
                    }
                }

                scm {
                    url = POM_SETTING_SCM_URL
                    connection = POM_SETTING_SCM_CONNECTION
                    developerConnection = POM_SETTING_SCM_DEV_CONNECTION
                }
            }
        }
    }

    signing {
        required {
            isReleaseBuild() && gradle.taskGraph.allTasks.any { it.name.startsWith("publish") }
        }
        sign publishing.publications
    }

    if (rootProject.extensions.findByName("nexusStaging") != null) {
        rootProject.nexusStaging {
            username getRepositoryUsername()
            password getRepositoryPassword()
        }
    }
}
